### ISSUE TITLE
ERROR - Cache file is missing (never successfully fetched?): bindRPZ/bindRPZcache-raw.githubusercontent.com_StevenBlack_hosts_master_hosts

### ISSUE THREAD

**Issue by pecastro** [glenpp/py-hole#7]
After tweaking the config file to make it run it stumbles upon the error.

```
pecastro@localhost /download/py-hole[master]$ ./py-hole-bind9RPZ  -c py-hole-bind9RPZ_config.yaml 
py-hole-bind9RPZ[1566142]: INFO - begin updating blocklists...
py-hole-bind9RPZ[1566142]: INFO - Creating cache directory: bindRPZ
py-hole-bind9RPZ[1566142]: INFO - processing https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
py-hole-bind9RPZ[1566142]: DEBUG - expire due to configured maximum cache time
py-hole-bind9RPZ[1566142]: INFO - fecthing (no or expired cache)
py-hole-bind9RPZ[1566142]: ERROR - Fetch sanity check failed
py-hole-bind9RPZ[1566142]: INFO - processing https://urlhaus.abuse.ch/downloads/rpz/
py-hole-bind9RPZ[1566142]: DEBUG - expire due to configured maximum cache time
py-hole-bind9RPZ[1566142]: INFO - fecthing (no or expired cache)
py-hole-bind9RPZ[1566142]: DEBUG - Writing file: bindRPZ/bindRPZcache-urlhaus.abuse.ch_downloads_rpz_
py-hole-bind9RPZ[1566142]: ERROR - Cache file is missing (never successfully fetched?): bindRPZ/bindRPZcache-raw.githubusercontent.com_StevenBlack_hosts_master_hosts
Cache file is missing (never successfully fetched?): bindRPZ/bindRPZcache-raw.githubusercontent.com_StevenBlack_hosts_master_hosts

```
Deleting the cache directory doesn't help.
But commenting the blacklist config section helps ...

```
py-hole-bind9RPZ[1568375]: INFO - begin updating blocklists...
py-hole-bind9RPZ[1568375]: INFO - processing https://urlhaus.abuse.ch/downloads/rpz/
py-hole-bind9RPZ[1568375]: DEBUG - no expire due to minimum cache time
py-hole-bind9RPZ[1568375]: INFO - processing cached file bindRPZ/bindRPZcache-urlhaus.abuse.ch_downloads_rpz_
py-hole-bind9RPZ[1568375]: INFO - Stats for https://urlhaus.abuse.ch/downloads/rpz/
py-hole-bind9RPZ[1568375]: INFO - + Total hosts: 968
py-hole-bind9RPZ[1568375]: INFO - Stats overall (all sources)
py-hole-bind9RPZ[1568375]: INFO -   Total hosts: 968
py-hole-bind9RPZ[1568375]: WARNING - Unused exclusion: do-not-tracker.org
py-hole-bind9RPZ[1568375]: WARNING - Unused exclusion: eviltracker.net
py-hole-bind9RPZ[1568375]: WARNING - Unused exclusion: stats.stackexchange.com
py-hole-bind9RPZ[1568375]: WARNING - Unused exclusion: trackersimulator.org
Traceback (most recent call last):
  File "./py-hole-bind9RPZ", line 857, in <module>
    main()
  File "./py-hole-bind9RPZ", line 844, in main
    category['_zone'].write()
  File "./py-hole-bind9RPZ", line 159, in write
    with open(temp_file, 'wt') as f_rpz:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/bind/db.rpz.example.com.TMP'
```

Also, it would be nice to have the capability of generating the RPZ file in a host which is not the target DNS server.
These recent changes make it slightly more difficult to do so.
I had to substitute the `rndc` commands in the config by `echo` which is still manageable but at the end instead of a single RPZ file I could pushinto my already configure BIND I was surprised to notice multiple.

**Comment by glenpp** [comment]
I think the big clue is "ERROR - Fetch sanity check failed" - check your system logs and it should have more detail. This is almost certainly configuration related in that the checks specified verify the data is sane are failing.
